listen_addresses = ['127.0.0.1:5353']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = false
require_dnssec = false
require_nolog = true
require_nofilter = true
disabled_server_names = []
proxy = 'socks5://127.0.0.1:7898'  # 需与 SmartDNS 的 proxy-server 地址完全匹配
force_tcp = true  # 【必改】配合 socks5 代理：强制用 TCP 传输（代理通常不支持 UDP）
http3 = false
timeout = 5000
keepalive = 30
cert_refresh_delay = 240
# bootstrap_resolvers = ['119.29.29.29:53', '223.5.5.5:53']  # 腾讯/阿里云 DNS（国内稳定，仅用于拉取服务器列表）
bootstrap_resolvers = ['9.9.9.11:53', '8.8.8.8:53']
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '9.9.9.9:53'
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 10
cache = false
#cache_size = 4096
#cache_min_ttl = 2400
#cache_max_ttl = 86400
#cache_neg_min_ttl = 60
#cache_neg_max_ttl = 600
[captive_portals]
[local_doh]
[query_log]
format = 'tsv'
[nx_log]
format = 'tsv'
[blocked_names]
[blocked_ips]
[allowed_names]
[allowed_ips]
[schedules]
[sources]
  [sources.public-resolvers]
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
    cache_file = 'public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''
  [sources.relays]
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md']
    cache_file = 'relays.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''
[broken_implementations]
fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']
[doh_client_x509_auth]
[anonymized_dns]
routes = [
   { server_name = '*', via = ['anon-cs-singapore'] },
#  { server_name = '*', via = ['anon-cs-singapore', 'anon-cs-tokyo'] },
   { server_name='dnscry.pt-anon-singapore02-ipv4', via=['sdns://gQ0xMDMuMTc5LjQ0Ljcz'] }
]
skip_incompatible = true
direct_cert_fallback = false
[dns64]
[static]